"""modify AdvertisingModel

Revision ID: 3e76cd86ed50
Revises: 5353126c4b9a
Create Date: 2022-01-07 05:19:10.778982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e76cd86ed50'
down_revision = '5353126c4b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
