"""ugrade UserModel

Revision ID: 52585dfffdcc
Revises: 8128754944b1
Create Date: 2022-01-05 23:02:04.531377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52585dfffdcc'
down_revision = '8128754944b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
