"""modify AdvertisingModel

Revision ID: 5353126c4b9a
Revises: 719e696d30e9
Create Date: 2022-01-07 05:07:21.147168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5353126c4b9a'
down_revision = '719e696d30e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
