"""add AdvertisingModel

Revision ID: 719e696d30e9
Revises: 80e83c2f7187
Create Date: 2022-01-07 05:04:04.694437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719e696d30e9'
down_revision = '80e83c2f7187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('advertisings_created_at', 'advertisings', ['created_at'], unique=False)
    op.create_index('advertisings_title', 'advertisings', ['title'], unique=False)
    op.create_index('users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_email', table_name='users')
    op.drop_index('advertisings_title', table_name='advertisings')
    op.drop_index('advertisings_created_at', table_name='advertisings')
    op.drop_table('advertisings')
    # ### end Alembic commands ###
