"""modify AdvertisingModel

Revision ID: 75aaa93a2aa0
Revises: 3e76cd86ed50
Create Date: 2022-01-07 06:22:41.087802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aaa93a2aa0'
down_revision = '3e76cd86ed50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
